import receiptConfig from "./config/receiptConfig.js";

export const cashboxData = {
  isOffline: false,
  dateTime: "2024-05-24T13:20:02.357Z",
  name: "ТОВ ТЕСТ ПРРО",
  pointName: 'Кафе "Мʼята"',
  pointAddress:
    "Дніпропетровська область, м. Дніпро, Амур-Нижньодніпровський район, вул. Шолом-Алейхема, 4, кв. (Офіс) 31",
  tin: "12345678",
  cashbox: "4000244601",
};
export const getServiceInputBodyMock = {
  sum: 2850,
  date: "16.05.2024",
  time: "19:28:35",
  receiptConfig,
  cashboxData,
};

export const getServiceOutputBodyMock = {
  sum: 750,
  date: "16.05.2024",
  time: "19:48:35",
  receiptConfig,
  cashboxData,
};

export const orderInfo = {
  orderNumber: 1650,
  orderType: "У закладі",
  openDate: "16 травня 2024 19:28:35",
  printDate: "16 травня 2024 19:29:35",
  tableId: 1,
  hallName: "Зал 1",
  guestAmount: 2,
};

export const productsData = [
  {
    barcodes: ["12345678"],
    marking: ["ADCC123123"],
    name: "2204109600#Вино игристое вкусное",
    count: 2,
    price: 130.02,
    taxPrograms: "ДГ",
  },
  {
    barcodes: null,
    marking: null,
    name: "2204888600#Сир",
    count: 4,
    price: 260,
    taxPrograms: "Д",
  },
];

export const taxesData = {
  total: 1300.04,
  card: 1100,
  cash: 200,
  taxes: [
    { name: "ПДВ Г 20%", value: 214.6, program: "Г" },
    { name: "Акцизний податок Д 5%", value: 12.38, program: "Д" },
  ],
};

export const roundData = [
  { name: "До сплати", value: 1300 },
  { name: "Заокруглення", value: 0.04 },
];

export const sstData = {
  adv: "ПриватБанк.",
  adv2p: "Беремо i робимо!",
  allResponses: { 2957: {} },
  amount: "1.68",
  applicationId: 2957,
  approvalCode: "159345",
  authCode: "159345",
  bankAcquirer: "ПриватБанк",
  captureReference: "",
  cardExpiryDate: "2709",
  date: "27.05.2024",
  deviceClass: "platformPayTerminal",
  deviceId: "2957_1171759599",
  discount: "0.00",
  fiscal_company_uuid: null,
  hstFld63Sf89: "",
  invoiceNumber: "1923984010",
  issuerName: "Visa Credit",
  merchant: "S1260S6Y",
  merchantId: "ПриватБанк",
  operationType: 1,
  pan: "4422********6333",
  paymentSystem: "VISA",
  paymentSystemName: "VISA",
  posConditionCode: "00",
  posEntryMode: "071",
  processingCode: "000000",
  receipt: "",
  receiptId: 1716822579300,
  responseCode: "0000",
  rrn: "083998389823",
  rrnExt: "414815005125",
  signVerif: "0",
  signVerify: "0",
  success: true,
  terminalId: "S1260S6Y",
  time: "18:10:12",
  track1: "",
  trnStatus: "1",
  txnType: "1",
};

export const footerData = {
  dfsDocumentFiscalId: "13eG45ty",
  dateTime: "16.05.2024 19:29:35",
  cashbox: cashboxData.cashbox,
  status: "ОНЛАЙН",
  docType: "ФІСКАЛЬНИЙ ЧЕК",
  software: "Poster POS",
};

// eslint-disable-next-line no-unused-vars
const expectedReceiptWithASCIIQR = [
  "              ТОВ ТЕСТ ПРРО             ",
  '              Кафе "Мʼята"              ',
  "  Дніпропетровська область, м. Дніпро,  ",
  "   Амур-Нижньодніпровський район, вул.  ",
  "    Шолом-Алейхема, 4, кв. (Офіс) 31    ",
  "               ІД 12345678              ",
  "----------------------------------------",
  "2204109600#                             ",
  "12345678                                ",
  "ADCC123123                              ",
  "Вино игристое 2 x 130,02   260,04   ДГ",
  "вкусное                               ",
  "",
  "2204888600#                             ",
  "Сир           4 x 260,00  1040,00    Д",
  "",
  "Готівкою                       200,00грн",
  "Карткою                       1100,00грн",
  "----------------------------------------",
  "Сума                          1300,04грн",
  "ПДВ Г 20%                         214,60",
  "Акцизний податок Д 5%              12,38",
  "----------------------------------------",
  "До сплати                     1300,00грн",
  "Заокруглення                     0,04грн",
  "",
  "----------------------------------------",
  "ПриватБанк                              ",
  "S1260S6Y                                ",
  "Оплата                                  ",
  "ЕПЗ                     4422********6333",
  "ПЛАТІЖНА СИСТЕМА                    VISA",
  "КОД АВТ.                          159345",
  "RRN                         083998389823",
  "КАСИР                      .............",
  "ДЕРЖАТЕЛЬ ЕПЗ              .............",
  "",
  "----------------------------------------",
  "                13eG45ty                ",
  "           16.05.2024 19:29:35          ",
  "               4000244601               ",
  "                 ОНЛАЙН                 ",
  "             ФІСКАЛЬНИЙ ЧЕК             ",
  "               Poster POS               ",
  " ▄▄▄▄▄ █▄▀ ▄ ▄██   █▀ █▄ ▄▀ ▄ █▀██ ▄▄▄▄▄",
  " █   █ ████▄▄  █▀█▀█▀▄▀▄▀▄▄█▀█▄▄▀█ █   █",
  " █▄▄▄█ ██ █ ▀▀▀█ ▄▄█▀ ▄ ▄▀▀▄█▀ ▄██ █▄▄▄█ ",
  "▄▄▄▄▄▄▄█ █ █▄█ ▀▄█ █ █▄▀ █ ▀▄█ █ █▄▄▄▄▄▄▄",
  "  ▀  ▀▄▀█▄▀  ▄▀▄▀▄█▄▀█ ▀▀▄▀▄▄▄  ██▄▀▀▀▀▀▄",
  "█▀ █ █▄▀  ▀▄▀ █ █▀▄ ▀██▄▄▄  ▄▀▀█  █▀ ▀▄▀▄",
  "█▄▄▄█▀▄▄ ▀ █  █▄▄▄  █▄ ▄█  ▀█ ▄▄█ █ ▀█▀  ",
  "▄▀  █ ▄ █▄ █ █▄▀▀ ▀▀ ▀▀ ▀█▄ ▀▄▀ █▄▄  ▄▄█ ",
  "█▄ ██▄▄ ▀▀█  ▄▄  ▀███▄█▄███ ▀▀▀▀▀██▄▀▄▄▀█",
  " █▄▄▄█▄▀▄▄▀▀▄█▄  █▄▄▄█ ▀ ▀▄▄███▄▄█ █▀▄ ▄▀",
  "██▀█▄ ▄█ ███▀▄▄ ██  ██ ███▄  █▀█ █▄▀▀▀ ▀▄",
  "▄ ▄█▀█▄█▄▀▄█▀▄█  ▀█  ▀ ▄▄▄▀  ▀█    █ ▀██▀",
  "▀▀ ▀▄ ▄▀█▄█ ▀ █ ▀█▀ ▄██ █ ▀  █▀▄ █  ▀   ▀",
  "█▄▀█ █▄   ▄▀▄██▀ ▄▄ ▄█▄  █▀▄█▄▀▄█▀  ██ ▄▄",
  "  ▄▄█▄▄▀▄ ▄▄▄█  █ █▀ ██ █▄█▄▀▄█▀▀▀▀▀▄▄███",
  "   ▄▀ ▄ ▀█▀▀ ▀▀ █▀ ▄▄██▀▄▀█ ███▀██▀█▀██▀ ",
  "▄▄█▄█▄▄█▀▄ ▀██▄▄▀▄▀ █▄█▀ ▄▀ █▄█  ▄▄▄ ██ ▀",
  " ▄▄▄▄▄ ██ ▄█ ▄  █▀▄ ▄███▀▄▀ ██▄  █▄█ ████",
  " █   █ █ ▀█ █   ▄▄ ▄▄█ ▄▀ ▀▀▄▄█▄  ▄▄▄▄▀▀▄",
  " █▄▄▄█ █▀██▀▀█▄ ▀▄█ ▀██ ▄█▄ ▀▄▀█▀▄▀▀▄▀ ▄ ",
  "       ▀  ▀ ▀     ▀▀    ▀   ▀▀   ▀ ▀▀▀ ▀▀",
].join("\n");

export const fiscalReceiptDataMock = {
  code: 200,
  result: {
    cashboxData,
    dfsDocumentFiscalId: "2462757750",
    type: "receipt",
    cashbox: cashboxData.cashbox,
    total: 384.26,
    payments: [
      {
        sum: 284.26,
        type: "cash",
      },
      {
        sum: 100,
        type: "card",
      },
    ],
    products: productsData,
    uid: "587989ce-f05d-4d66-b2a8-4138f13bfe88",
    dateTime: "2024-05-16T16:29:35.710Z",
    taxes: [
      {
        type: 5,
        name: "Акциз 5%",
        percent: 5,
        sum: 18.29,
        turnover: 384.26,
        sourceSum: 0,
        program: "Д",
      },
      {
        type: 4,
        name: "ПДВ 20%",
        percent: 20,
        sum: 29.25,
        turnover: 184.26,
        sourceSum: 0,
        program: "Г",
      },
    ],
    sstData,
  },
};
